# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d5ebdd016f264a6f4bf2336ff244f16a1a0ddbadce2820c974cb05a82f5d5cbfa92ea81641121400b98a0e030ed1e7b84ddf3917cfeb3699b1165fac77233ae

test:
  secret_key_base: b20f9016bb7caa5e726e277e669a4b3ec5afe4a2f3e86a2a7833be3a9befa1e5ad674f5f6e77fc7a88c26a2f9242e654ea953e0f234077281026da71463a7572

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
